server {
    listen       80;
    server_name  localhost;

    location /api/ {
        proxy_pass http://proxy:3000;
        proxy_set_header Host sman2mengwi.sch.id;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header User-Agent "Mozilla/5.0 (compatible; DwismaBot/1.0)";
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
